Allow user annotations and serviceAccountName
anycable/anycable-helm pull request #20
Opened 2022-02-11 22:46 UTC by invsblduck

# Background
I had the need to configure annotations for my AnyCable Service resource in EKS (specifically, to correctly configure a health-check for the ALB Ingress Controller), as well as Pod annotations for sidecar injection. The latter also required running the pod with a different ServiceAccount. I suppose other people may eventually need to do this as well.
 
This change adds new top-level keys to `values.yaml` which allow parameterization of Service annotations, Pod annotations, and Pod `serviceAccountName`.

(Deployment annotations were arbitrarily not added because I didn't need them.)

# Implementation Considerations

Most Deployment-related options are enumerated in `values.yaml` as top-level keys (for convenience, I presume). As is done with Ingress currently, I would have preferred to instead refactor all Deployment-related values to be nested under a `deployment` key, but didn't want to conflate concerns or change it without talking to you first.

But, instead of adding a top-level key named `serviceAnnotations`, Service annotations are configured similar to that of Ingress:
```yaml
    service:
      annotations:
        foo: bar
        baz: qux
```

Thanks.

2022-02-12 21:49 UTC, nepalez commented on anycable-go/templates/deployment.yml
> +      {{- end }}
```suggestion
      {{- if (.pod | default dict).serviceAccountName }}
      serviceAccountName: {{ pod.serviceAccountName }}
      {{- end }}
```

2022-02-12 21:54 UTC, nepalez commented on anycable-go/templates/deployment.yml
> +        {{- end }}
In this and the next comments I propose adding a `pod` group to keep the structure of values under control.

Here is some inconsistency provided compared to other pod-related settings like `.nodeSelector` etc. which are also related to the pod, but kept in the root of values.

I left them untouched for backward consistency, but later we can make another major release where this structure will be enforced for all pod-related settings.

2022-02-14 22:43 UTC, invsblduck commented on anycable-go/templates/deployment.yml
> +        {{- end }}
Awesome. That actually makes me a lot happier. :wink:  Thanks.

2022-02-15 10:25 UTC, nepalez requested changes
Could you apply my changes? Then I'd merge the PR

2022-02-17 17:20 UTC, sdhull commented on README.md
> +|**serviceAccountName**|User-specified ServiceAccount for Pod identity||
Updating the README to match PR review suggestions:
```suggestion
|**pod.annotations**|User-specified Pod annotations|`{}`|
|**pod.serviceAccountName**|User-specified ServiceAccount for Pod identity||
|**service.annotations**|User-specified Service annotations|`{}`|
```

2022-02-17 17:21 UTC, sdhull commented
@nepalez thanks for your help! Changes were applied, lmk if I missed anything 👍

2022-02-21 18:11 UTC, merged