Allow user to specify custom `command` and `args` for container
anycable/anycable-helm pull request #21
Opened 2022-02-11 22:59 UTC by invsblduck

This is useful in case operator wants to launch a shell first and customize the environment further. For example, external volumes (outside of Helm) may have been patched to the Pod by sidecars that were injected via mutating admission hooks.

2022-02-12 21:07 UTC, nepalez reviewed
Just a couple of small fixes
- you don't need to check the presence of keys before checking of their values
- I'd better quote the command to support `/bin/bash --verbose` etc.

2022-02-12 21:07 UTC, nepalez commented on anycable-go/templates/deployment.yml
> +          {{- if and (hasKey $values "command") (.command) }}
```suggestion
          {{- if .command }}
```

2022-02-12 21:07 UTC, nepalez commented on anycable-go/templates/deployment.yml
> +          {{- if and (hasKey $values "args") (.args) }}
```suggestion
          {{- if .args }}
```

2022-02-12 21:07 UTC, nepalez commented on anycable-go/templates/deployment.yml
> +            - {{ .command }}
```suggestion
            - {{ .command | quote }}
```

2022-02-14 22:48 UTC, invsblduck commented
> Just a couple of small fixes
> 
> * you don't need to check the presence of keys before checking their values
> 
> * I'd better quote the command to support values with symbols that can break yaml syntax. They can be quoted in a source values file, so we should quote them here

Thank you... first time working with Helm templates. I probably have PTSD from all templating languages from last 20 yrs. :)

Good recommendation for quoting. I used the `quote` filter at first, then removed it because it was triggering a bug in the version of Helm used by ArgoCD.

2022-02-15 10:25 UTC, nepalez requested changes
Could you apply my changes?

2022-02-21 18:10 UTC, merged